Implement Altair networking gossip spec (#2479)
* Implement Altair networking gossip spec

* Fix compilation error: Add snappyjs type

* SYNC_COMMITTEE_SUBNET_COUNT as a constant not param

* Preaggregate SyncCommitteeContribution, replace SyncCommittee repos by seen caches

* Only aggregate signatures one time, fulfill syncCommittee validation

* Remove unused db buckets

* Review syncCommittee validation

* Review PR

* Fix compilation errors and unit tests

Co-authored-by: dapplion <35266934+dapplion@users.noreply.github.com>