fix: request columns by peer custodied columns (#8330)
**Motivation**

- before we send `beacon_data_columns_by_root` or
`beacon_data_columns_by_range` to peer, we need to filter by peers'
custofied columns
- otherwise, will get error
```
Sep-05 03:05:17.827[sync]            debug: Error downloading in BlockInputSync.fetchBlockInput attempt=3, rootHex=0xe81f474d8bd7f94e891f664165f7ea3af9841ff3b7a17a20f9bc54647f5b0480, peer=16Uiu2HAm3k5Npu6EaYWxiEvzsdLseEkjVyoVhvbxWEuyqdBgBBbq, peerClient=Grandine, code=DOWNLOAD_BY_ROOT_ERROR_EXTRA_SIDECAR_RECEIVED, peer=16...BgBBbq, blockRoot=0xe81f…0480, invalidIndex=126
Error: Received a columnSidecar that was not requested
    at fetchAndValidateColumns (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:457:13)
    at fetchByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:197:26)
    at downloadByRoot (file:///usr/src/lodestar/packages/beacon-node/src/sync/utils/downloadByRoot.ts:71:49)
    at BlockInputSync.fetchBlockInput (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:512:21)
    at wrapError (file:///usr/src/lodestar/packages/beacon-node/src/util/wrapError.ts:18:32)
    at BlockInputSync.downloadBlock (file:///usr/src/lodestar/packages/beacon-node/src/sync/unknownBlock.ts:319:17)
```

**Description**

- fix for `downloadByRange` and `downloadByRoot` flows

Closes #8329

---------

Co-authored-by: Tuyen Nguyen <twoeths@users.noreply.github.com>